apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
spec:
  type: NodePort
  ports:
  - name: ngsi
    port: 1026
    targetPort: 1026
  selector:
    app: orion
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion:2.2.0
        command: [ '/usr/bin/contextBroker',
                   '-fg', '-multiservice', '-ngsiv1Autocast',
                   '-dbhost', 'mongodb', '-logLevel', 'DEBUG' ]
        ports:
        - containerPort: 1026
