# orion adapter handler config
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: h1
 namespace: istio-system
spec:
 adapter: orionadapter
 connection:
   address: "orionadapterservice:43210"
 params:
  # Pub/pvt key pair. The adapter only uses the pub key at the moment
  # to validate inbound JTW tokens.
  # WARNING: test keys, never put prod ones here since this file sits
  # in GitHub!
  idsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv
    vkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHc
    aT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIy
    tvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0
    e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb
    V6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9
    MwIDAQAB
    -----END PUBLIC KEY-----
  idsa_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWw
    kWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mr
    m/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEi
    NQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV
    3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2
    QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQABAoIBACiARq2wkltjtcjs
    kFvZ7w1JAORHbEufEO1Eu27zOIlqbgyAcAl7q+/1bip4Z/x1IVES84/yTaM8p0go
    amMhvgry/mS8vNi1BN2SAZEnb/7xSxbflb70bX9RHLJqKnp5GZe2jexw+wyXlwaM
    +bclUCrh9e1ltH7IvUrRrQnFJfh+is1fRon9Co9Li0GwoN0x0byrrngU8Ak3Y6D9
    D8GjQA4Elm94ST3izJv8iCOLSDBmzsPsXfcCUZfmTfZ5DbUDMbMxRnSo3nQeoKGC
    0Lj9FkWcfmLcpGlSXTO+Ww1L7EGq+PT3NtRae1FZPwjddQ1/4V905kyQFLamAA5Y
    lSpE2wkCgYEAy1OPLQcZt4NQnQzPz2SBJqQN2P5u3vXl+zNVKP8w4eBv0vWuJJF+
    hkGNnSxXQrTkvDOIUddSKOzHHgSg4nY6K02ecyT0PPm/UZvtRpWrnBjcEVtHEJNp
    bU9pLD5iZ0J9sbzPU/LxPmuAP2Bs8JmTn6aFRspFrP7W0s1Nmk2jsm0CgYEAyH0X
    +jpoqxj4efZfkUrg5GbSEhf+dZglf0tTOA5bVg8IYwtmNk/pniLG/zI7c+GlTc9B
    BwfMr59EzBq/eFMI7+LgXaVUsM/sS4Ry+yeK6SJx/otIMWtDfqxsLD8CPMCRvecC
    2Pip4uSgrl0MOebl9XKp57GoaUWRWRHqwV4Y6h8CgYAZhI4mh4qZtnhKjY4TKDjx
    QYufXSdLAi9v3FxmvchDwOgn4L+PRVdMwDNms2bsL0m5uPn104EzM6w1vzz1zwKz
    5pTpPI0OjgWN13Tq8+PKvm/4Ga2MjgOgPWQkslulO/oMcXbPwWC3hcRdr9tcQtn9
    Imf9n2spL/6EDFId+Hp/7QKBgAqlWdiXsWckdE1Fn91/NGHsc8syKvjjk1onDcw0
    NvVi5vcba9oGdElJX3e9mxqUKMrw7msJJv1MX8LWyMQC5L6YNYHDfbPF1q5L4i8j
    8mRex97UVokJQRRA452V2vCO6S5ETgpnad36de3MUxHgCOX3qL382Qx9/THVmbma
    3YfRAoGAUxL/Eu5yvMK8SAt/dJK6FedngcM3JEFNplmtLYVLWhkIlNRGDwkg3I5K
    y18Ae9n7dHVueyslrb6weq7dTkYDi3iOYRW8HRkIQh06wEdbxt0shTzAJvvCQfrB
    jg/3747WSsf/zBTcHihTRBdAv6OmdhV4/dD5YBfLAkLrd+mX7iE=
    -----END RSA PRIVATE KEY-----
  id_token_json_template: |
    {
      "@type": "ids:ResultMessage",
      "id": "http://industrialdataspace.org/resultMessage/1a421b8c-3407-44a8-aeb9-253f145c869a",
      "issued": "%s",
      "modelVersion": "2.1.0",
      "issuerConnector": "https://companyA.com/connector/59a68243-dd96-4c8d-88a9-0f0e03e13b1b",
      "securityToken": {
        "@type": "ids:DynamicAttributeToken",
        "tokenFormat": "https://w3id.org/idsa/code/tokenformat/JWT",
        "tokenValue": "%s"
      }
    }
  daps:
    server_host: "mockdaps:44300"
    connector_id: "4e16f007-d959-4eb2-b47d-78dd0c4eab0e"
    connector_audience: "https://consumerconnector.fiware.org"
    seconds_before_expiry: 3600
    #
    # mTLS certs and keys in PEM format:
    # * connector's own private key
    # * connector's own certificate to authenticate with DAPS; paired to
    #   the private key
    # * DAPS server certificate the connector should use to authenticate
    #   the server.
    # To test with our DAPS mock server the below keys/certs have to
    # match those in the mock server config as explained in: 'mock.go'.
    #
    # WARNING: these are test keys/certs, never put prod ones here since
    # this file sits in GitHub!
    #
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC1L/lt6gVKZINB
      76kwBYv6EYX9jYGkX2tBuCK36B0GVUXATfEfsO6U0bgJnF82UtE8Nr19A8VsVuYP
      TGycUtR3Z2iUwAqwBihmPDD3XdeKrFzS23KEf1OcwplbVFsUBiypMNuxii9KP2IO
      eFczNeNv1DUGSNK2e4XkhbGFylCW+Yev39pxYLI4hT8F8JNEuDwX7fQk/cO3cNzE
      /A9Tkmx9Ssfc/coKdC02T/53KmllqaooJrcLTJW2kwM9x5r+u1U3A/8K7uJA2eNi
      kwv3aRbFdH+2bl+Tjkn+akL44rZVIJGl5JvnRQwoEL+Vvo0ZrQ+iFLiSA2R9ldc/
      NLJa6FeDAgMBAAECggEACYp0LPiEvM0cKE2xcAjqvQlNL/PSntAzeqtykJKVbK7y
      1FSGXO/ZMFb2xPLKBLdJs00Cn2GidLkCtk2E7pph+8OjOyn9phU87V1ACtaTMgcv
      gB70Icv+oCOTJb8EaMKGeYZMG0Y2hUdfJ3noxZaR2mKnRCRzjA5nF4h+t5fWtIxq
      doDh6j33i0d0l+3K9nR1EP4K46FkUNSjVmbJhOTYU9q8H4ewZ2RzgknGcRWNhV5z
      M4/X37FfVO85Jn2kWaPx3NxFtGUXqzbCsYPnNaY/lhhfJdXNNlu9Qi1NyAdEDJFU
      wwYRi66y6CABttojCzilDRv73BFlbwf611ZG5qACmQKBgQDrP48pe1RTlLe4Hac+
      SihKW2G0mFkgkxj9dp3VnbduxOXbKwrz5GaIZaD+o+BeYmqjRiryKBhvcq7xZb00
      r6ko/xhFcPeomvYCrNg1sm1FVyLD02I5xNodolDISH9VagZofQ1S8sJzeytiZNzJ
      metSJ6rpy7LDUtrkbq3Ss7zgnQKBgQDFK5j8sOuF8A+0zBGhOAcKetCm+4YBHQCy
      WWluxhL7S2rJXXhLM2qssp56FjOFavQ1sLlFLnrEsaNgklNU7fIWy2ImmT0sa8Y2
      S3UzeXhZ5jMUOLsQW23zsP7Z6c0U0hMpzQRYVEKbutk1z6Qga/k1JqjwOgTaZztK
      si2Kpf1OnwKBgB+WiUKorMoMTh8K3Eog6wgQ/S2ix1T4a4KdStREOT1Gcxba0L2v
      DZWDD/shRh9mV6tU4K9jcuSEIbmIT7+jVrOKjVfFs3uQUzhIvT94lfOZn7Fr0OSw
      6hjQkshR88ckVXfyUrewoSugflLX+E2ZvV9qtChwkbBoj7vcoLqKJ/KBAoGBAIA6
      C0OC15kCd2RwNqLvafzRxHJkL1D4CKT0axHkdSHCeU89n2bgqGZpv5DMcXM6DFoC
      dWrdgG/8yrCaWOFp4cAbQtixXcxOxtg2mKECRVfJ0rw67MUFgOsz13nmiD4bJOVR
      dJrxKWRXzr0lLar8LVT4sHOSd+eFrVS1rdJ2gtcnAoGAYwcT3uVWoPNcZHrnaYDi
      Eo1+9kd8vS5mr5bgIOJ1nS9np4Bg6qDyTtgVZHanIjXw/1UZ4tRKbqd0mC+ZfFNP
      N6kAg1/mvAdO45ZwCd2DJbNC8/U5e7lAxcqJBKp/i0VwmeAcZyfXDttD6epNsuOM
      wSWFX8pQTNWseFTkRvJEShM=
      -----END PRIVATE KEY-----
    connector_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDVjCCAj4CCQDp28MTQXuiwjANBgkqhkiG9w0BAQsFADBtMQswCQYDVQQGEwJa
      QTEVMBMGA1UECAwMV2VzdGVybiBDYXBlMRIwEAYDVQQHDAlDYXBlIFRvd24xEjAQ
      BgNVBAoMCVJ1c2tzIEx0ZDELMAkGA1UECwwCTWExEjAQBgNVBAMMCWxvY2FsaG9z
      dDAeFw0yMDAxMTQxNjI0MzVaFw0zMDAxMTExNjI0MzVaMG0xCzAJBgNVBAYTAlpB
      MRUwEwYDVQQIDAxXZXN0ZXJuIENhcGUxEjAQBgNVBAcMCUNhcGUgVG93bjESMBAG
      A1UECgwJUnVza3MgTHRkMQswCQYDVQQLDAJNYTESMBAGA1UEAwwJbG9jYWxob3N0
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtS/5beoFSmSDQe+pMAWL
      +hGF/Y2BpF9rQbgit+gdBlVFwE3xH7DulNG4CZxfNlLRPDa9fQPFbFbmD0xsnFLU
      d2dolMAKsAYoZjww913Xiqxc0ttyhH9TnMKZW1RbFAYsqTDbsYovSj9iDnhXMzXj
      b9Q1BkjStnuF5IWxhcpQlvmHr9/acWCyOIU/BfCTRLg8F+30JP3Dt3DcxPwPU5Js
      fUrH3P3KCnQtNk/+dyppZamqKCa3C0yVtpMDPcea/rtVNwP/Cu7iQNnjYpML92kW
      xXR/tm5fk45J/mpC+OK2VSCRpeSb50UMKBC/lb6NGa0PohS4kgNkfZXXPzSyWuhX
      gwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBTqJskNcwTM1WxJrC14oWLuekvA4fE
      Ugu2RhLLjhmK16mRGn9QE2/N7lE1TdJ8xX0NhyYeKR9dosOxMIRDNI3z+gKw8qJO
      /UrKavgcbZsJH+OQiNZ64iIgeq6AsdEcDD8bs2QjdldttgLTALZ8d66bbLhjwn0j
      GZpXKhhs/24Oi/vlDOyXh538HNXq5UddkRcRLdl9arocEwNDy4NpsbVPXeVIrok0
      0tsc6KvwtAjsjWpEjgOI0Pl0+l4hA0MoMLxV15onKeCi7JQaLaP8tmNlXHFj9qu+
      X5UpiCO6e/pce8I5RwyQEKjpcyDNyWaUk1Z1xwYEzUcxtvvYxpUpyOOx
      -----END CERTIFICATE-----
    server_certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDVjCCAj4CCQDp28MTQXuiwjANBgkqhkiG9w0BAQsFADBtMQswCQYDVQQGEwJa
      QTEVMBMGA1UECAwMV2VzdGVybiBDYXBlMRIwEAYDVQQHDAlDYXBlIFRvd24xEjAQ
      BgNVBAoMCVJ1c2tzIEx0ZDELMAkGA1UECwwCTWExEjAQBgNVBAMMCWxvY2FsaG9z
      dDAeFw0yMDAxMTQxNjI0MzVaFw0zMDAxMTExNjI0MzVaMG0xCzAJBgNVBAYTAlpB
      MRUwEwYDVQQIDAxXZXN0ZXJuIENhcGUxEjAQBgNVBAcMCUNhcGUgVG93bjESMBAG
      A1UECgwJUnVza3MgTHRkMQswCQYDVQQLDAJNYTESMBAGA1UEAwwJbG9jYWxob3N0
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtS/5beoFSmSDQe+pMAWL
      +hGF/Y2BpF9rQbgit+gdBlVFwE3xH7DulNG4CZxfNlLRPDa9fQPFbFbmD0xsnFLU
      d2dolMAKsAYoZjww913Xiqxc0ttyhH9TnMKZW1RbFAYsqTDbsYovSj9iDnhXMzXj
      b9Q1BkjStnuF5IWxhcpQlvmHr9/acWCyOIU/BfCTRLg8F+30JP3Dt3DcxPwPU5Js
      fUrH3P3KCnQtNk/+dyppZamqKCa3C0yVtpMDPcea/rtVNwP/Cu7iQNnjYpML92kW
      xXR/tm5fk45J/mpC+OK2VSCRpeSb50UMKBC/lb6NGa0PohS4kgNkfZXXPzSyWuhX
      gwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBTqJskNcwTM1WxJrC14oWLuekvA4fE
      Ugu2RhLLjhmK16mRGn9QE2/N7lE1TdJ8xX0NhyYeKR9dosOxMIRDNI3z+gKw8qJO
      /UrKavgcbZsJH+OQiNZ64iIgeq6AsdEcDD8bs2QjdldttgLTALZ8d66bbLhjwn0j
      GZpXKhhs/24Oi/vlDOyXh538HNXq5UddkRcRLdl9arocEwNDy4NpsbVPXeVIrok0
      0tsc6KvwtAjsjWpEjgOI0Pl0+l4hA0MoMLxV15onKeCi7JQaLaP8tmNlXHFj9qu+
      X5UpiCO6e/pce8I5RwyQEKjpcyDNyWaUk1Z1xwYEzUcxtvvYxpUpyOOx
      -----END CERTIFICATE-----
---

# instance for authorization template
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
 name: icheck
 namespace: istio-system
spec:
 template: oriondata
 params:
   client_token: request.headers["header"]
---

# rule to dispatch to orion handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: r1
 namespace: istio-system
spec:
 actions:
 - handler: h1.istio-system
   instances:
   - icheck
   name: adapter_response
 responseHeaderOperations:
  - name: fiware-ids-server-token
    values: [ adapter_response.output.context_broker_token ]
---
